---

- hosts: webserver
  become: yes

  vars:
    php_version: "7.2"

  environment:
    COMPOSER_MEMORY_LIMIT: -1

  roles:
    - name: geerlingguy.repo-remi
      when: ansible_os_family == "RedHat"
    - geerlingguy.apache
    - geerlingguy.php-versions
    - geerlingguy.php
    - geerlingguy.php-mysql
    - geerlingguy.git
    - geerlingguy.composer
    - symlink
    - geerlingguy.drush
    - geerlingguy.drupal-console
    - geerlingguy.drupal
    - perms-fix
    - Islandora-Devops.drupal-openseadragon
    - webserver-app
    - Islandora-Devops.riprap
    - Islandora-Devops.bagger
    - Islandora-Devops.matomo
    - Aplyca.S3fs

