---

# Change selinux status to permissive
disable_selinux: yes

islandora_extra_ubuntu_packages:
  - wget
  - curl
  - htop
  - tree
  - zsh
  - fish
  - unzip
  - build-essential
  - vim
  - python3-mysqldb

islandora_extra_centos_packages:
  - wget
  - curl
  - tree
  - zsh
  - unzip
  - vim
  - make
  - automake
  - gcc
  - gcc-c++
  - kernel-devel

postgresql_user: postgres
drupal_db_user: drupal8
drupal_db_name: drupal8

mysql_users:
  - name: "{{ drupal_db_user }}"
    host: "%"
    password: "{{ drupal_db_password }}"
    priv: "{{ drupal_db_name }}.*:ALL"

# Used by both the webserver and crayfish role for CentOS.
php_enablerepo: "remi-php72"
php_packages_state: "latest"
httpd_conf_directory: "/etc/apache2"
httpd_conf_directory_enabled: "{{httpd_conf_directory}}/conf-enabled"
drush_path: "/usr/local/bin/drush"
crayfish_drupal_base_url: "http://{{ hostvars[groups['webserver'][0]].ansible_host }}:{{ apache_listen_port }}"
# crayfish_db_host: "35.163.226.190"
# crayfish_db_host: "127.0.0.1"
crayfish_gemini_base_url: "http://{{ hostvars[groups['crayfish'][0]].ansible_host }}:{{ apache_listen_port }}/gemini"
# crayfish_db_root_password: "{{ islandora_db_root_password }}"
# triplestore_namespace: islandora
# alpaca_triplestore_base_url: "http://http://52.13.108.39:8080/bigdata"
# alpaca_milliner_base_url: "http://{{ hostvars[groups['webserver'][0]] }}:{{ apache_listen_port }}/milliner/"
# alpaca_gemini_base_url: "http://{{ hostvars[groups['webserver'][0]] }}:{{ apache_listen_port }}/gemini"
# alpaca_houdini_base_url: "http://{{ hostvars[groups['webserver'][0]] }}:{{ apache_listen_port }}/houdini"
# alpaca_homarus_base_url: "http://{{ hostvars[groups['webserver'][0]] }}:{{ apache_listen_port }}/homarus"
# apache_listen_port: 80
claw_db: 'mysql'
crayfish_db: "{{ claw_db }}"
# crayfish_db_root_user: 'mysql'
# crayfish_db_root_password: "{{ drupal_db_password }}"
fedora_base_url: "http://52.13.108.39:8080/fcrepo/rest/"
crayfish_fedora_base_url: "http://52.13.108.39:8080/fcrepo/rest/"
crayfish_gemini_fedora_base_url: "{{ crayfish_fedora_base_url }}"
s3fs:
  source: "https://github.com/s3fs-fuse/s3fs-fuse/archive/v1.85.tar.gz"
  buckets:
    - mountpoint: /mnt/s3fs
      bucket: s3fs
      accessKeyId: "{{ aws_access_key }}"
      secretAccessKey: "{{ aws_secret_key }}"
      options: "allow_other,use_cache=/tmp,max_stat_cache_size=100000,uid=33,gid=33,umask=002,url=https://asulibdev-islandora-bucket.s3.amazonaws.com"
