---

tomcat8_users:
  - username: islandora
    password: "{{ islandora_tomcat_password }}"
    roles:
      - manager-gui

# For production use either "jdbc-mysql" or "jdbc-postgresql"
#fcrepo_persistence: file-simple
fcrepo_persistence: jdbc-mysql-s3

# Used for mysql or postgres object persistence.
fcrepo_db_name: fcrepo
fcrepo_db_user: fcrepo
fcrepo_db_host: "islandora-fedora.cvznsvixsvec.us-west-2.rds.amazonaws.com"
fcrepo_db_port: "3306"
fcrepo_db_password: "{{ fcrepo_db_password }}"
fcrepo_db_root_user: fcrepo
fcrepo_db_root_password: "{{ fcrepo_db_password }}"
cantaloupe_symlink: "/opt/cantaloupe"

tomcat8_java_opts:
  - -Djava.awt.headless=true
  - -Dfile.encoding=UTF-8
  - -server
  - -Xms512m
  - -Xmx1024m
  - -XX:NewSize=256m
  - -XX:MaxNewSize=256m
  - -XX:PermSize=256m
  - -XX:MaxPermSize=256m
  - -Dfcrepo.home={{ fcrepo_home_dir }}
  - -Dfcrepo.modeshape.configuration=file://{{ fcrepo_home_dir }}/configs/repository.json
  - -Dfcrepo.activemq.configuration=file://{{ fcrepo_config_dir }}/activemq.xml
  - -Dfcrepo.spring.configuration=file://{{ fcrepo_home_dir }}/configs/fcrepo-config.xml
  - -Dfcrepo.external.content.allowed={{ fcrepo_allowed_external_content_file }}
  - -Dcom.bigdata.rdf.sail.webapp.ConfigParams.propertyFile={{ blazegraph_home_dir }}/conf/RWStore.properties
  - -Dcantaloupe.config={{ cantaloupe_symlink }}/cantaloupe.properties
  - -Dorg.apache.tomcat.util.buf.UDecoder.ALLOW_ENCODED_SLASH=true
  - -Daws.bucket={{fcrepo_aws_bucket}}
  - -Daws.accessKeyId={{aws_access_key}}
  - -Daws.secretKey={{aws_secret_key}}
  - -Daws.endPoint="https://s3.wasabisys.com"

fcrepo_syn_tomcat_home: "{{ tomcat8_home }}"
fcrepo_syn_default_public_key_path: "{{ fcrepo_syn_tomcat_home }}/conf/public.key"

fcrepo_syn_sites:
  - algorithm: RS256
    encoding: PEM
    anonymous: true
    default: true
    path: "{{ fcrepo_syn_default_public_key_path }}"
    url: https://35.166.140.245
  - algorithm: RS256
    encoding: PEM
    anonymous: true
    default: true
    path: "{{ fcrepo_syn_default_public_key_path }}"
    url: https://35.163.77.215
  - algorithm: RS256
    encoding: PEM
    anonymous: true
    default: true
    path: "{{ fcrepo_syn_default_public_key_path }}"

fcrepo_syn_tokens:
  - user: admin
    roles:
      - admin
      - fedoraAdmin
    token: "{{ islandora_syn_token }}"

fcrepo_version: "5.1.0"
fcrepo_auth_header_name: "X-Islandora"
fcrepo_syn_auth_header: "X-Islandora"
