crayfish_version_tag: 1.0.0

crayfish_services:
  - Gemini
  - Houdini
  - Milliner
  - Hypercube
  - Homarus
  - Recast

# Temporary to allow Silex/Symfony 4 differences
crayfish_silex_services:
  - Gemini
  - Milliner
  - Hypercube
  - Homarus
  - Recast

crayfish_symfony_services:
  - Houdini

crayfish_install_dir: /var/www/html/Crayfish

crayfish_syn_token: islandora

crayfish_log_directory: /var/log/islandora

# possible options: mysql, pgsql
crayfish_db: mysql
crayfish_pgsql_user: postgres
crayfish_db_user: crayfish
crayfish_db_password: islandora
crayfish_db_name: gemini
crayfish_db_driver: "{% if crayfish_db == 'mysql' %}pdo_mysql{% elif crayfish_db == 'pgsql' %}pdo_pgsql{% endif %}"
crayfish_db_port: "{% if crayfish_db == 'mysql' %}3306{% elif crayfish_db == 'pgsql' %}5432{% endif %}"

crayfish_fedora_base_url: http://localhost:8080/fcrepo/rest
crayfish_drupal_base_url: http://localhost:8000
crayfish_gemini_base_url: http://localhost:8000/gemini

# Gemini default config
crayfish_gemini_log_file: /var/log/islandora/gemini.log
crayfish_gemini_log_level: DEBUG

crayfish_gemini_debug: TRUE

crayfish_gemini_fedora_base_url: "{{ crayfish_fedora_base_url }}"

crayfish_gemini_jwt_enabled: TRUE
crayfish_gemini_jwt_config: "{{ crayfish_install_dir }}/syn-settings.xml"

crayfish_gemini_db_options:
  driver: "{{ crayfish_db_driver }}"
  host: 127.0.0.1
  port: "{{ crayfish_db_port }}"
  dbname: "{{ crayfish_db_name }}"
  user: "{{ crayfish_db_user }}"
  password: "{{ crayfish_db_password }}"

# Houdini default config
crayfish_houdini_log_file: /var/log/islandora/houdini.log
crayfish_houdini_log_level: DEBUG

crayfish_houdini_jwt_enabled: TRUE
crayfish_houdini_jwt_config: "{{ crayfish_install_dir }}/syn-settings.xml"

crayfish_houdini_fedora_base_url: "{{ crayfish_fedora_base_url }}"

crayfish_houdini_executable_config:
  executable: convert
  formats:
    valid:
      - image/jpeg
      - image/png
      - image/tiff
      - image/jp2
    default: image/jpeg

# Hypercube default config
crayfish_hypercube_log_file: /var/log/islandora/hypercube.log
crayfish_hypercube_log_level: DEBUG

crayfish_hypercube_jwt_enabled: TRUE
crayfish_hypercube_jwt_config: "{{ crayfish_install_dir }}/syn-settings.xml"

crayfish_hypercube_fedora_base_url: "{{ crayfish_fedora_base_url }}"
crayfish_hypercube_tesseract_executable: tesseract
crayfish_hypercube_pdftotext_executable: pdftotext

# Milliner default config
crayfish_milliner_log_file: /var/log/islandora/milliner.log
crayfish_milliner_log_level: DEBUG

crayfish_milliner_jwt_enabled: TRUE
crayfish_milliner_jwt_config: "{{ crayfish_install_dir }}/syn-settings.xml"

crayfish_milliner_debug: TRUE

crayfish_milliner_fedora_base_url: "{{ crayfish_fedora_base_url }}"
crayfish_milliner_drupal_base_url: "{{ crayfish_drupal_base_url }}"
crayfish_milliner_gemini_base_url: "{{ crayfish_gemini_base_url }}"
crayfish_milliner_modified_date_predicate: http://schema.org/dateModified
crayfish_milliner_strip_format_jsonld: true

crayfish_milliner_db_options:
  driver: "{{ crayfish_db_driver }}"
  host: 127.0.0.1
  port: "{{ crayfish_db_port }}"
  dbname: "{{ crayfish_db_name }}"
  user: "{{ crayfish_db_user }}"
  password: "{{ crayfish_db_password }}"

# OS Dependent variables set in vars can be overridden here
# crayfish_user: www-data
# httpd_conf_directory: /etc/apache2
# crayfish_packages:
#   - ImageMagick

php_packages_extra:
  - php7.0-mysql
  - php7.0-pgsql


# homarus
crayfish_homarus_log_file: /var/log/islandora/homarus.log
crayfish_homarus_log_level: DEBUG

crayfish_homarus_jwt_enabled: TRUE
crayfish_homarus_jwt_config: "{{ crayfish_install_dir }}/syn-settings.xml"

crayfish_homarus_fedora_base_url: "{{ crayfish_fedora_base_url }}"

crayfish_homarus_executable_config:
  executable: ffmpeg
  mime_types:
    valid:
      - video/mp4
      - video/x-msvideo
      - video/ogg
      - audio/x-wav
      - audio/mpeg
      - audio/aac
      - image/jpeg
    default: video/mp4
  mime_to_format:
    valid:
      - video/mp4_mp4
      - video/x-msvideo_avi
      - video/ogg_ogg
      - audio/x-wav_wav
      - audio/mpeg_mp3
      - audio/aac_m4a
      - image/jpeg_image2pipe
    default: mp4

# recast
crayfish_recast_log_file: /var/log/islandora/recast.log
crayfish_recast_log_level: DEBUG

crayfish_recast_jwt_enabled: TRUE
crayfish_recast_jwt_config: "{{ crayfish_install_dir }}/syn-settings.xml"

crayfish_recast_fedora_base_url: "{{ crayfish_fedora_base_url }}"
crayfish_recast_drupal_base_url: "{{ crayfish_drupal_base_url }}"
crayfish_recast_gemini_base_url: "{{ crayfish_gemini_base_url }}"

crayfish_recast_prefixes:
  acl: "http://www.w3.org/ns/auth/acl#"
  fedora: "http://fedora.info/definitions/v4/repository#"
  ldp: "http://www.w3.org/ns/ldp#"
  memento: "http://mementoweb.org/ns#"
  pcdm: "http://pcdm.org/models#"
  pcdmuse: "http://pcdm.org/use#"
  webac: "http://fedora.info/definitions/v4/webac#"
  vcard: "http://www.w3.org/2006/vcard/ns#"
